# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: oracle-actions/setup-java@v1
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        website: oracle.com
        release: 17
    - name: Build with Maven
      run: mvn clean test
